name: clang-format Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format in the fox folder
      uses: jidicula/clang-format-action@v4.3.1
      with:
        clang-format-version: '12'
        check-path: 'fox'
    - name: Run clang-format in the tests folder
      uses: jidicula/clang-format-action@v4.3.1
      with:
        clang-format-version: '12'
        check-path: 'tests'
