name: linux-integration-testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: compile
        run: |
          bash .ci/compile.sh
      - name: run tests
        run: |
         bash .ci/test.sh 
