name: windows-integration-testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.4.0
        with:
          submodules: true
          fetch-depth: 0
      - name: compile
        run: |
          .ci\compile.ps1
      - name: run tests
        run: |
          .ci/test.ps1
